# 📊 Data Exploration: College Major Salaries

**Project 72/100 – Python Data Challenge**

In this project, I explore salary data across different college majors using Pandas.  
The goal is to analyze starting salaries, mid-career earnings, risk levels, and salary spread across categories (STEM, Business, HASS).

Tools used:
- Python
- Pandas
- Anaconda
- Jupyter Notebook

Let’s explore what majors have the highest earning potential — con toda la energía 🇨🇴

## 🔹 1. Importing Libraries

In [1]:
import pandas as pd

## 🔹 2. Loading the Dataset

We begin by loading the dataset and inspecting its structure.

In [2]:
df = pd.read_csv('salaries_by_college_major.csv')
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

In [3]:
df.shape

(51, 6)

In [4]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='str')

## 🔹 3. Missing Values and Junk Data

Before performing analysis, we check for missing values.  
Missing data can affect calculations and lead to incorrect conclusions.

In [5]:
df.isna().sum()

Undergraduate Major                  0
Starting Median Salary               1
Mid-Career Median Salary             1
Mid-Career 10th Percentile Salary    1
Mid-Career 90th Percentile Salary    1
Group                                1
dtype: int64

### Handling missing values

Since the last row contains missing values, we remove it using `.dropna()`.

In [6]:
clean_df = df.dropna()

In [7]:
clean_df.isna().sum()

Undergraduate Major                  0
Starting Median Salary               0
Mid-Career Median Salary             0
Mid-Career 10th Percentile Salary    0
Mid-Career 90th Percentile Salary    0
Group                                0
dtype: int64

## 🔹 4. Accessing Columns and Individual Cells in a Dataframe

### Find College Major with Highest Starting Salaries

In [8]:
clean_df['Starting Median Salary'].max()

np.float64(74300.0)

### Finding the ID for the maximum value

In [9]:
clean_df['Starting Median Salary'].idxmax()

43

### Name of the Major with Highest Starting Salaries

In [10]:
clean_df.loc[43]

Undergraduate Major                  Physician Assistant
Starting Median Salary                           74300.0
Mid-Career Median Salary                         91700.0
Mid-Career 10th Percentile Salary                66400.0
Mid-Career 90th Percentile Salary               124000.0
Group                                               STEM
Name: 43, dtype: object

### Find College Major with Highest Mid-Career Salaries

In [11]:
highest_median_salary=clean_df['Mid-Career Median Salary'].idxmax()

In [12]:
clean_df.loc[highest_median_salary]

Undergraduate Major                  Chemical Engineering
Starting Median Salary                            63200.0
Mid-Career Median Salary                         107000.0
Mid-Career 10th Percentile Salary                 71900.0
Mid-Career 90th Percentile Salary                194000.0
Group                                                STEM
Name: 8, dtype: object

### Find College Major with Lowest Starting Salaries

In [13]:
lowest_starting_salary=clean_df['Starting Median Salary'].idxmin()

In [14]:
clean_df.loc[lowest_starting_salary]

Undergraduate Major                  Spanish
Starting Median Salary               34000.0
Mid-Career Median Salary             53100.0
Mid-Career 10th Percentile Salary    31000.0
Mid-Career 90th Percentile Salary    96400.0
Group                                   HASS
Name: 49, dtype: object

### Find College Major with Lowest Mid-Career Salaries

In [15]:
lowest_median_salary=clean_df['Mid-Career Median Salary'].idxmin()

In [16]:
clean_df.loc[lowest_median_salary]

Undergraduate Major                  Education
Starting Median Salary                 34900.0
Mid-Career Median Salary               52000.0
Mid-Career 10th Percentile Salary      29300.0
Mid-Career 90th Percentile Salary     102000.0
Group                                     HASS
Name: 18, dtype: object

## 🔹 5. Sorting Values & Adding Columns: Majors with the Most Potential vs Lowest Risk

### Lowest Risk Majors

To measure salary risk, we calculate the difference between the 90th percentile and 10th percentile salaries.

A smaller spread = lower income uncertainty.  
A larger spread = higher variability and risk.

In [17]:
spread_col = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']
clean_df.insert(1, 'Spread', spread_col)

In [18]:
clean_df.head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,109800.0,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,113700.0,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,104200.0,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,85400.0,41600.0,76800.0,50600.0,136000.0,Business

### Sorting by the Lowest Spread

In [19]:
low_risk = clean_df.sort_values('Spread')
low_risk[['Undergraduate Major', 'Spread']].head()

           Undergraduate Major   Spread
40                     Nursing  50700.0
43         Physician Assistant  57600.0
41                   Nutrition  65300.0
49                     Spanish  65400.0
27  Health Care Administration  66400.0

### Top 5 degrees with the highest values in the 90th percentile.

In [20]:
top_5 = clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending=False)
top_5[['Undergraduate Major', 'Mid-Career 90th Percentile Salary']].head()

     Undergraduate Major  Mid-Career 90th Percentile Salary
17             Economics                           210000.0
22               Finance                           195000.0
8   Chemical Engineering                           194000.0
37                  Math                           183000.0
44               Physics                           178000.0

### Majors with the Greatest Spread in Salaries

In [21]:
highest_spread = clean_df.sort_values('Spread', ascending=False)
highest_spread[['Undergraduate Major', 'Spread']].head()

   Undergraduate Major    Spread
17           Economics  159400.0
22             Finance  147800.0
37                Math  137800.0
36           Marketing  132900.0
42          Philosophy  132500.0

Notice how 3 of the top 5 are present in both. This means that there are some very high earning Economics degree holders out there, but also some who are not earning as much

## 🔹 6. Grouping and Pivoting Data with Pandas

To better understand salary differences by academic field, we group the data by category:
- STEM
- Business
- HASS

In [22]:
clean_df.groupby('Group').count()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,,
Business,12,12,12,12,12,12
HASS,22,22,22,22,22,22
STEM,16,16,16,16,16,16

### Average salary by group

For better readability it is used: pd.options.display.float_format = '{:,.2f}'.format

In [23]:
pd.options.display.float_format = '{:,.2f}'.format
clean_df.groupby('Group').mean(numeric_only=True)

,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,
Business,"103,958.33","44,633.33","75,083.33","43,566.67","147,525.00"
HASS,"95,218.18","37,186.36","62,968.18","34,145.45","129,363.64"
STEM,"101,600.00","53,862.50","90,812.50","56,025.00","157,625.00"

STEM majors show the highest average mid-career salaries.
HASS majors have the lowest average starting salaries.
Business majors show competitive 90th percentile earnings.

## 🧠 Final Conclusions

- STEM degrees dominate mid-career earnings.
- Business majors show strong high-end earning potential.
- HASS majors generally start with lower salaries.
- Some majors (like Economics and Finance) show very high salary spread, meaning high risk but also high reward.

This project strengthened my understanding of:
- Data cleaning
- Indexing & filtering
- Sorting & grouping
- Adding calculated columns
- Exploratory Data Analysis (EDA)